/**
 * Russian language pack for the DSH web interface.
 * Registered as the `ru` locale for every UI namespace.
 * Bundle id: dsh-locale-ru (see package.json "dsh.client").
 */
window.__ModuleLoader__.load({
	id: "dsh-locale-ru",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

		//#region dictionaries
		/** Russian dictionaries per namespace (29 namespaces, 703 keys). */
		const DICTIONARIES = {
			"command": {
			"listbox.aria": "Совпадения /{command}",
			"overlay.aria": "Варианты /{command}",
			"search.aria": "Фильтр вариантов",
			"search.placeholder": "Поиск…",
			"status.applying": "Применение…",
			"status.empty": "Нет вариантов",
			"status.loading": "Загрузка вариантов…"
		},
			"common": {
			"back": "Назад",
			"cancel": "Отмена",
			"close": "Закрыть",
			"collapse": "Свернуть",
			"copied": "Скопировано",
			"copy": "Копировать",
			"delete": "Удалить",
			"edit": "Изменить",
			"expand": "Развернуть",
			"load.failed": "Не удалось загрузить",
			"loading": "Загрузка…",
			"more": "Ещё",
			"next": "Далее",
			"none": "Нет",
			"ok": "ОК",
			"previous": "Предыдущий",
			"retry": "Повторить",
			"save": "Сохранить",
			"search": "Поиск",
			"skip": "Пропустить",
			"submit": "Отправить",
			"submitting": "Отправка…",
			"truncated": "Сокращено",
			"unknown": "Неизвестно"
		},
			"conversation": {
			"access.confirm.acknowledge": "Я понимаю риски и хочу продолжить",
			"access.confirm.cancel": "Отмена",
			"access.confirm.description": "Полный доступ сокращает шаги подтверждения и позволяет агенту выполнять больше действий напрямую, включая чувствительные операции, изменения файлов и внешние команды. Используйте его, только если доверяете текущей задаче.",
			"access.confirm.enable": "Включить полный доступ",
			"access.confirm.title": "Включить полный доступ?",
			"approval.allowOnce": "Разрешить один раз",
			"approval.detail.aria": "Подробности подтверждения",
			"approval.escalation": "Инструмент {toolName} запрашивает привилегированное выполнение",
			"approval.reject": "Отклонить",
			"approval.waiting": "Ожидание подтверждения",
			"ask.answered": "Отвечено {answered}/{total}",
			"ask.cancelled": "отменено",
			"ask.interrupted": "прервано",
			"ask.rowTitle": "Задать вопрос",
			"ask.waiting": "ожидание",
			"bash.failed": "Ошибка",
			"bash.running": "Выполняется",
			"bash.stopped": "Остановлено",
			"chat.loadError": "Не удалось загрузить историю: {message} ({code})",
			"chat.loadOlder": "Загрузить более ранние",
			"chat.loadingHistory": "Загрузка истории…",
			"chat.toBottom": "Вниз",
			"clock.md": "{m}/{d}",
			"clock.ymd": "{y}-{m}-{d}",
			"command.done": "Завершено",
			"command.failed": "Команда не выполнена",
			"command.running": "Выполняется…",
			"command.title": "Команда",
			"context.aria": "Использовано {percent} контекста",
			"context.messages": "Сообщения",
			"context.system": "Системный промпт",
			"context.tools": "Инструменты",
			"context.used": "контекста использовано",
			"details.close": "Закрыть подробности",
			"details.empty": "Нажмите на строку инструмента в потоке сообщений, чтобы увидеть подробности",
			"details.input": "Вход",
			"details.notInWindow": "Этот вызов вне текущего окна",
			"details.output": "Выход",
			"details.running": "Выполняется…",
			"details.title": "Подробности",
			"duration.minutes": "{minutes} мин {seconds} с",
			"duration.seconds": "{seconds} с",
			"hero.chooseWorkspace": "Выбрать рабочую папку",
			"hero.headline": "В неизведанное",
			"hero.preview": "Предпросмотр",
			"hint.goal": "опишите цель для длительной задачи",
			"hint.goal.active": "цель активна — изменить / пауза / возобновить / сбросить",
			"image.closePreview": "Закрыть просмотр оригинального изображения",
			"image.dropBlocked": "Сейчас нельзя добавить изображения",
			"image.dropDesc": "До {count} изображений, {size} каждое",
			"image.dropTitle": "Перетащите изображения сюда, чтобы добавить их",
			"image.fileTooLarge": "Каждое изображение должно быть меньше {size}",
			"image.label": "Изображение",
			"image.loadFailed": "Не удалось загрузить изображение; нажмите, чтобы повторить",
			"image.loading": "Загрузка изображения…",
			"image.modelUnsupported": "Текущая модель не поддерживает изображения; переключитесь на модель, которая их поддерживает",
			"image.openOriginal": "Просмотреть оригинал",
			"image.openOriginalLabel": "{label}, нажмите, чтобы просмотреть оригинал",
			"image.original": "Оригинальное изображение",
			"image.pending": "Ожидающие изображения",
			"image.preview": "Просмотр оригинального изображения",
			"image.remove": "Удалить изображение {name}",
			"image.scrollLeft": "Прокрутить изображения влево",
			"image.scrollRight": "Прокрутить изображения вправо",
			"image.sendFailed": "Не удалось отправить изображения ({reason}); добавьте их снова и повторите",
			"image.serviceUnavailable": "Служба загрузки изображений недоступна",
			"image.subagentUnsupported": "Сеансы субагентов пока не поддерживают изображения",
			"image.tooMany": "Сообщение может содержать до {count} изображений",
			"image.tooManyPixels": "Слишком высокое разрешение изображения; сожмите его и попробуйте снова",
			"image.totalTooLarge": "Суммарный размер изображений превышает {size}; удалите часть и попробуйте снова",
			"image.unsupportedType": "Поддерживаются только изображения PNG, JPG, WebP и GIF",
			"input.accessMode": "Режим прав доступа, сейчас: {name}",
			"input.commands": "Команды",
			"input.send": "Отправить сообщение",
			"input.stop": "Остановить генерацию",
			"json.truncated": "… сокращено, всего {total} символов",
			"message.branch": "Ветвь в новый чат",
			"message.branchUnavailable": "Доступно только для последнего сообщения завершённого хода",
			"message.compaction": "Контекст сжат",
			"message.compaction.completed": "Сжато {items} элементов истории (~{tokens} токенов)",
			"message.compaction.expand": "Посмотреть сводку сжатия",
			"message.compaction.running": "Сжатие контекста…",
			"message.compaction.unavailable": "Сводка сжатия недоступна",
			"message.context.catalog.more": "… ещё {count}",
			"message.context.catalog.replaced": "Заменяющий каталог",
			"message.context.instructions.added": "добавлено",
			"message.context.instructions.loaded": "загружено",
			"message.context.instructions.removed": "удалено",
			"message.context.instructions.updated": "обновлено",
			"message.context.recall.counts": "{retained} сохранено · {omitted} опущено",
			"message.context.recall.truncated": "сокращено",
			"message.context.relay.from": "Из сеанса {session}",
			"message.context.snapshot.supersedes": "Заменяет более ранние снимки",
			"message.contextInjection": "Внедрение контекста",
			"message.contextRecall": "Восстановление сеанса",
			"message.extraBlock": "Дополнительный блок содержимого",
			"message.maxTokens": "Достигнут лимит токенов на ответ",
			"message.maxTokens.hint": "Ответ был обрезан; более ранний вывод сохранён в чате. Отправьте «продолжай», чтобы модель возобновила работу.",
			"message.ranFor": "Выполнялось {duration}",
			"message.retry.active": "Повтор запроса к модели",
			"message.retry.cancelled": "Повтор запроса к модели отменён",
			"message.retry.delay": "Задержка повтора: ",
			"message.retry.failure": "Причина ошибки: ",
			"message.retry.scheduled": "Ожидание повтора запроса к модели",
			"message.retry.started": "Запрос к модели повторён",
			"message.retry.status": "{label} ({retry}/{maximum}) · {seconds} с",
			"message.stopped": "Остановлено",
			"message.tokensPerSecond": "{tps} ток/с",
			"message.ttft": "TTFT {seconds} с",
			"message.turnError": "Этот ход завершился ошибкой",
			"message.unknownBlock": "Неизвестный блок содержимого",
			"message.unknownSurface": "Неизвестное событие поверхности: {type}",
			"placeholder.default": "Напишите агенту",
			"placeholder.hero": "Опишите, что хотите создать",
			"placeholder.parentOffline": "Родительский сеанс недоступен; отправка невозможна, но выполнение можно остановить",
			"placeholder.steerQueue": "Cmd/Ctrl+Enter направляет все сообщения из очереди",
			"placeholder.unavailable": "Сеанс недоступен",
			"placeholder.workspace": "Выберите рабочую папку, чтобы начать",
			"queue.cancelEdit": "Отменить редактирование",
			"queue.count": "Сообщений в очереди: {n}",
			"queue.edit": "Изменить сообщение в очереди",
			"queue.edit.unsupported": "Содержит нетекстовое содержимое; редактирование пока не поддерживается",
			"queue.editFailed": "Не удалось изменить: возможно, сообщение уже начало отправку.",
			"queue.remove": "Удалить сообщение из очереди",
			"queue.removeFailed": "Не удалось удалить: возможно, сообщение уже начало отправку.",
			"queue.save": "Сохранить сообщение в очереди",
			"queue.steer": "Направить сообщение из очереди",
			"queue.steer.unavailable": "Направление доступно только пока агент выполняется",
			"queue.steerFailed": "Не удалось направить. Попробуйте ещё раз.",
			"row.failed": "Ошибка",
			"row.running": "Выполняется",
			"row.stopped": "Остановлено",
			"session.hierarchy": "Иерархия сеансов",
			"settings.enter.description": "Только когда занято; Cmd/Ctrl+Enter использует другое поведение",
			"settings.enter.queue": "В очередь",
			"settings.enter.steer": "Направлять",
			"settings.enter.title": "Поведение Enter при занятости",
			"stats.cacheHit": "Попадание в кэш {percent}%",
			"stats.counts": "{turns} ходов · {steps} шагов",
			"stats.llm": "LLM {duration}",
			"stats.tokens": "Вход {input} ток · Выход {output} ток",
			"stats.tokensPerSecond": "{throughput} ток/с",
			"stats.toolCall": "Вызов инструмента {duration}",
			"stats.ttftAverage": "TTFT в среднем {duration}",
			"terminal.collapseAria": "Свернуть вывод",
			"terminal.done": "Готово",
			"terminal.exitCode": "код выхода {code}",
			"terminal.expandAria": "Развернуть оставшиеся {n} строк вывода",
			"terminal.expandRest": "… ещё {n} строк",
			"terminal.failed": "Ошибка",
			"terminal.noOutput": "Нет вывода",
			"terminal.running": "Выполняется",
			"terminal.signal": "сигнал {signal}",
			"todo.completed": "Выполнено {done}/{total}",
			"todo.progress.active": "{active} в работе",
			"todo.progress.done": "{done} выполнено",
			"todo.progress.pending": "{pending} ожидает",
			"todo.rowTitle": "Обновить список задач",
			"todo.title": "Задачи",
			"view.chat": "Чат"
		},
			"cordis": {
			"a11y.defining": "Определение плагина",
			"a11y.failed": "Определение не удалось",
			"a11y.stopped": "Определение прервано",
			"action.approve": "Разрешить",
			"action.approveOnce": "Разрешить только эту версию",
			"action.approvePlugin": "Разрешать будущие версии этого плагина",
			"action.decline": "Отклонить",
			"action.remove": "Удалить",
			"action.retry": "Повторить",
			"action.rollback": "Откатить",
			"action.run": "Запустить",
			"action.stop": "Остановить",
			"body.clientCode": "Клиент",
			"body.copied": "Скопировано",
			"body.copy": "Копировать",
			"body.hostCode": "Хост",
			"body.output": "Результат",
			"body.source": "Исходный код плагина",
			"panel.approvals.aria": "Подтверждения Cordis",
			"panel.current": "Сейчас: {packageId}",
			"panel.empty": "Плагины ещё не определены",
			"panel.group.current": "Этот сеанс",
			"panel.group.others": "Другие сеансы",
			"panel.hint": "Управление запуском — в панели Cordis над настройками",
			"panel.loading": "Чтение…",
			"panel.next": "Далее: {packageId}",
			"panel.plugins.aria": "Плагины Cordis",
			"panel.readFailed": "Не удалось прочитать список плагинов: {message}",
			"panel.runningCount": "выполняется: {count}",
			"panel.title": "Плагины Cordis",
			"panel.trigger": "Плагин Cordis",
			"panel.version": "Версия",
			"purpose.missing": "(назначение не указано)",
			"render.failedAbdicated": "Не удалось отрисовать в {slot}; восстановлен интерфейс по умолчанию:",
			"render.failedHeld": "Не удалось отрисовать в {slot}:",
			"row.defineTitle": "Зарегистрировать плагин Cordis",
			"row.removeTitle": "Удалить плагин Cordis",
			"row.runTitle": "Запустить плагин Cordis",
			"row.stopTitle": "Остановить плагин Cordis",
			"row.updateTitle": "Обновить плагин Cordis",
			"run.removed": "Этот пакет больше не существует",
			"run.superseded": "Новая карточка запуска доступна ниже",
			"status.awaitingApproval": "Ожидает подтверждения",
			"status.clientPending": "Клиент готов к активации",
			"status.failed": "Запуск не удался",
			"status.idle": "Готов",
			"status.removed": "Удалён",
			"status.running": "Выполняется",
			"status.superseded": "Доступна новая версия"
		},
			"deliverables": {
			"produced.label": "Результаты",
			"produced.more": "+ {count} файлов",
			"produced.moreOne": "+ 1 файл",
			"produced.open": "Открыть {name}",
			"produced.showInFolder": "Показать в папке"
		},
			"directory-browser": {
			"browser.cancel": "Отмена",
			"browser.create": "Создать",
			"browser.createIn": "Новая папка в «{name}»",
			"browser.editPath": "Изменить путь",
			"browser.folderName": "Имя папки",
			"browser.home": "Домой",
			"browser.loading": "Загрузка…",
			"browser.newFolder": "Новая папка",
			"browser.open": "Открыть",
			"browser.showHidden": "Показывать скрытые файлы",
			"browser.title": "Выберите рабочую папку",
			"browser.truncated": "Слишком много папок для отображения; показано только начало списка.",
			"browser.untitledFolder": "Папка без имени"
		},
			"feedback": {
			"action.dislike": "Плохой ответ",
			"action.dislikeActive": "Убрать оценку",
			"action.like": "Хороший ответ",
			"action.likeActive": "Убрать оценку",
			"error.conflict": "Отзыв изменён в другом месте; показано последнее состояние",
			"error.generic": "Не удалось сохранить отзыв",
			"error.load": "Не удалось загрузить отзыв",
			"note.aria": "Заметка об ответе",
			"note.cancel": "Отмена",
			"note.open": "Добавить заметку",
			"note.placeholder": "Что было хорошо или что пошло не так? (необязательно)",
			"note.save": "Сохранить"
		},
			"goal": {
			"action.cancel": "Отменить правку",
			"action.clear": "Сбросить цель",
			"action.edit": "Изменить цель",
			"action.pause": "Поставить на паузу",
			"action.resume": "Возобновить",
			"action.save": "Сохранить цель",
			"commandInput.aria": "Ввод команды",
			"objective.aria": "Цель задачи",
			"phase.active": "Активная цель",
			"phase.blocked": "Заблокированная цель",
			"phase.paused": "Пауза цели"
		},
			"job": {
			"count.idle.one": "{count} фоновая задача",
			"count.idle.other": "{count} фоновых задач",
			"count.live.one": "{count} фоновая задача выполняется",
			"count.live.other": "{count} фоновых задач выполняется",
			"duration.hours": "{hours} ч {minutes} мин",
			"duration.minutes": "{minutes} мин {seconds} с",
			"duration.seconds": "{seconds} с",
			"duration.title.done": "Заняло {duration}",
			"duration.title.live": "Выполняется {duration}",
			"list.aria": "Фоновые задачи",
			"status.completed": "завершена",
			"status.failed": "не выполнена",
			"status.killed": "отменена",
			"status.running": "выполняется",
			"status.stopping": "останавливается"
		},
			"model": {
			"action.reload": "Перезагрузить",
			"blocked.composer": "Эта модель недоступна — выберите другую, чтобы продолжить",
			"command.description": "Выбрать модель для этого чата",
			"effort.providerDefault": "По умолчанию",
			"empty.efforts": "У этой модели нет уровней рассуждений.",
			"empty.models": "Нет доступных моделей.",
			"error.action": "Ошибка операции с моделью: {message}",
			"menu.aria": "Модель и уровень рассуждений",
			"menu.effort": "Уровень рассуждений",
			"menu.model": "Модель",
			"option.loadError": "Не удалось загрузить каталог: {message}",
			"status.loading": "Обновление списка моделей…",
			"trigger.aria": "Выбрать модель, сейчас {model}",
			"trigger.ariaEffort": "Выбрать модель, сейчас {model}, уровень рассуждений {effort}",
			"trigger.fallback": "Выбрать модель",
			"trigger.selectAria": "Выбрать модель",
			"warning.groupLoad": "Не удалось загрузить {name}: {message}"
		},
			"permission.access": {
			"confirm.acknowledge": "Я понимаю риски и хочу продолжить",
			"confirm.cancel": "Отмена",
			"confirm.description": "Полный доступ сокращает шаги подтверждения и позволяет агенту выполнять больше действий напрямую, включая чувствительные операции, изменения файлов и внешние команды. Используйте его, только если доверяете текущей задаче.",
			"confirm.enable": "Включить полный доступ",
			"confirm.title": "Включить полный доступ?"
		},
			"plan": {
			"chip.off.aria": "Режим плана выключен, нажмите, чтобы включить",
			"chip.off.title": "Режим плана выключен — нажмите, чтобы включить (/plan)",
			"chip.on.aria": "Режим плана включён, нажмите, чтобы выключить",
			"chip.on.title": "Режим плана включён — нажмите, чтобы выключить (/plan off)"
		},
			"question": {
			"action.next": "Далее",
			"action.skip": "Пропустить вопрос",
			"custom.placeholder": "Введите ответ",
			"error.incomplete": "Сначала ответьте на этот вопрос.",
			"error.unanswered": "Выберите вариант или введите свой ответ.",
			"nav.cancel": "Закрыть все вопросы",
			"nav.maximize": "Развернуть карточку вопроса",
			"nav.minimize": "Свернуть карточку вопроса",
			"nav.next": "Следующий вопрос",
			"nav.prev": "Предыдущий вопрос",
			"option.recommended": "Рекомендуется",
			"plan.approve": "Одобрить",
			"plan.decline": "Отклонить",
			"plan.discuss": "Обсудить",
			"plan.header": "Проверка плана"
		},
			"session-log-download": {
			"dialog.close": "Закрыть",
			"dialog.commandFailed": "Не удалось запустить экспорт сеанса.",
			"dialog.errorTitle": "Не удалось экспортировать сеанс",
			"dialog.preparingDescription": "Готовится ZIP-архив с этим сеансом, его подсеансами и вложениями.",
			"dialog.preparingTitle": "Экспорт сеанса",
			"dialog.successDescription": "Браузер скачивает ZIP-архив сеанса.",
			"dialog.successTitle": "Загрузка сеанса началась"
		},
			"settings": {
			"close": "Закрыть",
			"general.nav": "Основные",
			"openDocument": "Открыть файл конфигурации",
			"openDocument.error": "Не удалось открыть файл конфигурации",
			"title": "Настройки",
			"trigger": "Настройки"
		},
			"settings.agentPreset": {
			"brokenBadge": "Не удалось загрузить",
			"brokenNoCopy": "Пресет, который не загрузился, нельзя дублировать",
			"builtIn": "Встроенный",
			"builtInGroup": "Встроенные",
			"cancel": "Отмена",
			"close": "Закрыть",
			"composition": "Композиция (agent.cordis.yml)",
			"copyIntro": "Весь пресет будет скопирован на этом компьютере. Идентификатор станет именем каталога, изменить его позже нельзя; остальное редактируется прямо в файлах пресета.",
			"copyOf": "Копия из",
			"copyTitle": "Дублировать пресет",
			"create": "Создать",
			"creating": "Создание…",
			"creatorDraft": "Создайте свой пресет в режиме создателя",
			"customGroup": "Свои",
			"delete": "Удалить",
			"deleteConfirm": "Удалить",
			"deleteDescription": "Каталог пресета будет удалён. Уже запущенные на нём сеансы не пострадают; новые сеансы больше не смогут его выбрать.",
			"deleteTitle": "Удалить этот пресет?",
			"deleting": "Удаление…",
			"description": "Применяется к чатам, которые вы начнёте с этого момента. Активные чаты сохраняют пресет, с которым были начаты.",
			"displayName": "Название",
			"displayNamePlaceholder": "Отображается в выборе; по умолчанию — идентификатор",
			"duplicate": "Дублировать",
			"duplicateUnavailable": "В этом развёртывании нет доступного для записи каталога пресетов",
			"error": "Не удалось загрузить пресеты агента.",
			"headerHint": "Пресет агента, с которым работает этот чат, задан при его запуске",
			"idInvalid": "Используйте строчные буквы, цифры и дефисы, начиная с буквы или цифры.",
			"idRequired": "Укажите идентификатор пресета.",
			"idTaken": "Пресет с таким идентификатором уже существует.",
			"inUse": "Используется",
			"loading": "Загрузка пресетов…",
			"nav": "Пресеты агента",
			"noDescription": "Без описания.",
			"openLocation": "Открыть папку",
			"presetCodeDescription": "Обладает всеми возможностями стандартного режима и представляет инструменты через Code Mode SDK, позволяя модели компоновать многошаговые операции одной TypeScript-программой.",
			"presetCodeName": "Режим PTC",
			"presetCordisDescription": "Для создания собственных пресетов агента: все возможности стандартного режима плюс проверки во время выполнения, эксперименты с плагинами и рекомендации по созданию пресетов.",
			"presetCordisName": "Режим создателя",
			"presetId": "Идентификатор",
			"presetIdPlaceholder": "my-agent",
			"presetMinimalDescription": "Кодинг-агент только с двумя инструментами: постоянной оболочкой bash и str_replace_editor.",
			"presetMinimalName": "Минимальный режим",
			"presetStandardDescription": "Полнофункциональный кодинг-агент с поддержкой редактирования файлов, оболочки, поиска по файлам и в интернете, навыков, планов, целей, субагентов и рабочих процессов.",
			"presetStandardName": "Стандартный режим",
			"retry": "Повторить",
			"revealedPathLabel": "Файлы пресета:",
			"seatHint": "Пресет агента для чата, который вы собираетесь начать",
			"sectionIntro": "Пресет — это сборка плагинов, в которой работает агент сеанса: его инструменты, промпты и возможности. Скопируйте существующий пресет и доработайте его под себя или используйте «режим создателя», чтобы агент создал его за вас.",
			"setDefault": "Сделать пресетом по умолчанию",
			"showLocation": "Показать расположение",
			"title": "Пресет агента",
			"userTrust": "Свой",
			"view": "Просмотр"
		},
			"settings.locale": {
			"language.title": "Язык"
		},
			"settings.models": {
			"add": "Добавить провайдера",
			"addModel": "Добавить модель",
			"advancedHint": "Остальные поля находятся в settings.yaml; редактируйте этот раздел напрямую.",
			"apply": "Применить",
			"applying": "Применение…",
			"baseUrl": "Базовый URL",
			"baseUrlDefault": "По умолчанию у провайдера",
			"cancel": "Отмена",
			"close": "Закрыть",
			"conflict": "Кто-то ещё изменил эти настройки, пока карточка была открыта. Закройте и снова откройте её, чтобы редактировать текущие значения.",
			"contextWindow": "Контекстное окно",
			"contextWindowPlaceholder": "Если пусто, используется значение провайдера по умолчанию",
			"create": "Создать провайдера",
			"creating": "Создание…",
			"credentialConfigured": "Ключ API настроен",
			"credentialMissing": "Ключ API отсутствует",
			"customAdd": "Добавить своего провайдера",
			"customApi": "Протокол API",
			"customApiUnset": "Не выбран",
			"customDisplayName": "Отображаемое имя",
			"customNeedsBaseUrl": "Для своего провайдера требуется базовый URL.",
			"customNeedsModels": "У своего провайдера должна быть хотя бы одна модель.",
			"customRoute": "Идентификатор провайдера",
			"customRouteHint": "Идентификатор в нижнем регистре, начинающийся с буквы, уникально именующий этого провайдера в запросах и как имя учётных данных.",
			"customRouteInvalid": "Начните со строчной буквы; далее строчные буквы, цифры и дефисы.",
			"customRouteTaken": "Этот идентификатор уже использует другой провайдер.",
			"customTag": "Свой",
			"customTitle": "Свой провайдер",
			"customized": "Изменённые настройки",
			"deleteConfirm": "Удалить {provider}",
			"deleteDescription": "Удаление {provider} удалит его конфигурацию. Используемые им учётные данные хранятся отдельно и будут сохранены.",
			"deleteDescriptionWithCredential": "Удаление {provider} удалит его конфигурацию и сохранённый ключ API.",
			"deleteTitle": "Удалить {provider}?",
			"deleting": "Удаление {provider}…",
			"edit": "Изменить",
			"editProvider": "Изменить {provider}",
			"fetchAdopt": "Добавить выбранные",
			"fetchDescription": "Это модели, доступные у провайдера. Выберите те, которые нужно добавить.",
			"fetchEmpty": "Провайдер не указал ни одной модели. Добавьте их вручную.",
			"fetchModels": "Загрузить доступные модели",
			"fetchNeedsBaseUrl": "Сначала введите базовый URL, затем загружайте.",
			"fetchTitle": "Выберите модели для добавления",
			"fetching": "Запрос к провайдеру…",
			"intro": "Введите ключи API, чтобы использовать модели следующих провайдеров.",
			"keyBlank": "Введите ключ API или оставьте поле пустым, чтобы сохранить текущий.",
			"keyBlankNew": "Введите ключ API или оставьте поле пустым, если этот провайдер аутентифицируется иначе.",
			"keyEnvLocked": "Предоставлен средой запуска (только для чтения)",
			"keyIllegalCharacters": "Ключ API имеет недопустимый формат. Проверьте его.",
			"keyInput": "Ключ API",
			"keyPlaceholder": "Введите ключ API",
			"keyPlaceholderNative": "Введите ключ API или оставьте поле пустым, чтобы использовать аутентификацию из окружения",
			"keyRequired": "Введите ключ API, чтобы продолжить.",
			"keyStored": "Настроен — введите новое значение для замены",
			"loadFailed": "Не удалось загрузить каталог провайдеров",
			"maxTokens": "Макс. токенов на ответ",
			"maxTokensPlaceholder": "Если пусто, используется значение провайдера по умолчанию",
			"model": "Модель",
			"modelAdvanced": "Возможности",
			"modelCapacityInvalid": "Значение ёмкости должно быть числом, при необходимости с суффиксом K или M.",
			"modelContextInvalid": "Контекстное окно должно быть положительным числом, например 131072, 256K или 1M.",
			"modelContextWindow": "Контекстное окно",
			"modelDuplicate": "Каждый идентификатор модели может встречаться один раз.",
			"modelId": "Идентификатор модели",
			"modelIdDuplicate": "Идентификатор модели должен быть уникальным.",
			"modelIdRequired": "Требуется идентификатор модели.",
			"modelMaxTokens": "Макс. токенов на ответ",
			"modelMaxTokensInvalid": "Максимум токенов на ответ должен быть положительным числом, например 8192, 64K или 1M.",
			"modelName": "Отображаемое имя",
			"modelNameInvalid": "Отображаемое имя не может быть пустым.",
			"modelNamePlaceholder": "Если пусто, используется идентификатор модели",
			"models": "Модели",
			"modelsCustomized": "Изменённый каталог моделей",
			"modelsEmpty": "В селекторе не будет отображаться ни одной модели. Идентификаторы, отсутствующие в списке, можно отправлять напрямую.",
			"modelsInherited": "Используются настройки адаптера по умолчанию",
			"nav": "Модели",
			"onboardingDescription": "Настройте официального провайдера DeepSeek, чтобы начать работу.",
			"onboardingLater": "Настроить позже",
			"onboardingSave": "Сохранить и продолжить",
			"onboardingSaving": "Сохранение…",
			"onboardingTitle": "Добавьте ключ API, чтобы начать",
			"provider": "Провайдер",
			"readOnly": "В этом развёртывании документ настроек доступен только для чтения.",
			"remove": "Удалить",
			"removeModel": "Удалить модель",
			"removeProvider": "Удалить {provider}",
			"resetModels": "Вернуть настройки по умолчанию",
			"retry": "Повторить",
			"savedProvider": "Провайдер {provider} сохранён.",
			"title": "Модели",
			"welcomeError": "Не удалось сохранить подтверждение. Попробуйте ещё раз."
		},
			"settings.permission": {
			"confirm.acknowledge": "Я понимаю риски и хочу продолжить",
			"confirm.cancel": "Отмена",
			"confirm.description": "Полный доступ сокращает шаги подтверждения в новых чатах и позволяет выполнять больше действий напрямую, включая чувствительные операции, изменения файлов и внешние команды. Используйте его, только если доверяете последующим задачам.",
			"confirm.enable": "Включить полный доступ",
			"confirm.title": "Включить полный доступ?",
			"description": "Выберите режим прав по умолчанию для новых чатов",
			"loading": "Загрузка",
			"title": "Права доступа",
			"unavailable": "Недоступно"
		},
			"settings.pluginInventory": {
			"active": "Смонтирован",
			"catalog": "Список плагинов",
			"configuration": "Конфигурация",
			"cordis": "Статус Cordis",
			"disabledTag": "Отключён",
			"empty": "Нет доступных плагинов.",
			"emptySearch": "Нет подходящих плагинов.",
			"enabledTag": "Включён",
			"error": "Плагины временно недоступны.",
			"failed": "Ошибка монтирования",
			"loading": "Чтение плагинов…",
			"loadingPhase": "Загрузка",
			"pending": "Ожидание зависимостей",
			"retry": "Повторить",
			"search": "Поиск плагинов",
			"tab": "Список плагинов",
			"unloading": "Выгрузка",
			"unobserved": "Не смонтирован"
		},
			"settings.plugins": {
			"agentLoopDescription": "Как агент отправляет вызовы инструментов.",
			"agentLoopMaxParallel": "Параллельные вызовы инструментов",
			"agentLoopMaxParallelHint": "Верхняя граница параллельно-безопасных вызовов, выполняемых одновременно в рамках одного шага.",
			"agentLoopTitle": "Цикл агента",
			"bashDescription": "Ограничивает каждую команду, которую запускает агент.",
			"bashMaxOutputBytes": "Лимит вывода на поток (байт)",
			"bashMaxOutputBytesHint": "Вывод сверх лимита сохраняется во временный файл, а не теряется.",
			"bashTimeoutMs": "Тайм-аут команды (мс)",
			"bashTimeoutMsHint": "Как долго одна команда может выполняться до завершения.",
			"bashTitle": "Оболочка",
			"collapse": "Скрыть настройки",
			"configurableTab": "Конфигурация плагинов",
			"discard": "Отменить",
			"empty": "Это развёртывание не предоставляет настроек плагинов.",
			"expand": "Показать настройки",
			"intro": "Настройка и просмотр плагинов, установленных в этом развёртывании.",
			"invalidNumber": "Введите число или оставьте поле пустым, чтобы использовать значение по умолчанию.",
			"nav": "Плагины",
			"overridden": "Переопределено",
			"readOnly": "В этом развёртывании настройки хранятся только для чтения.",
			"reset": "Сбросить к значению по умолчанию",
			"save": "Сохранить",
			"saveFailed": "Развёртывание не приняло эти значения; они оставлены для исправления.",
			"saving": "Сохранение…",
			"tabs": "Виды плагинов",
			"title": "Плагины",
			"unsaved": "Не сохранено",
			"webSearchApiKey": "Ключ API",
			"webSearchApiKeyHint": "Хранится вне файла настроек. Оставьте пустым, чтобы сохранить текущий ключ.",
			"webSearchApiKeySet": "Ключ настроен.",
			"webSearchApiKeyUnset": "Ключ не настроен; поиск недоступен, пока он не будет задан.",
			"webSearchBaseUrl": "Адрес",
			"webSearchBaseUrlHint": "Оставьте пустым, чтобы использовать адрес провайдера по умолчанию.",
			"webSearchDescription": "Поисковый провайдер DeepSeek.",
			"webSearchMaxUses": "Макс. поисков за запрос",
			"webSearchMaxUsesHint": "Сколько раз один запрос может выполнять поиск, прежде чем должен ответить.",
			"webSearchTitle": "Поиск в интернете"
		},
			"settings.theme": {
			"appearance.dark": "Тёмная",
			"appearance.light": "Светлая",
			"appearance.system": "Системная",
			"appearance.title": "Оформление"
		},
			"sidebar": {
			"session.new": "Новый чат",
			"session.new.label": "Новый чат",
			"toggle.collapse": "Свернуть боковую панель",
			"toggle.open": "Открыть боковую панель"
		},
			"skill": {
			"menu.userOnly": "только для пользователя",
			"row.failed": "Не удалось загрузить навык",
			"row.instructions": "Инструкции",
			"row.running": "Загрузка навыка",
			"row.stopped": "Загрузка навыка прервана"
		},
			"slash.menu": {
			"command": "Команды",
			"loading": "Загрузка…",
			"skill": "Навыки",
			"subagent": "Субагенты",
			"suggestions.aria": "Подсказки для команд"
		},
			"subagent": {
			"activity.inactive": "не выполняется",
			"activity.running": "выполняется",
			"branch.collapse": "Свернуть потомков {label}",
			"branch.expand": "Развернуть потомков {label}",
			"count.running.one": "{count} субагент выполняется",
			"count.running.other": "{count} субагентов выполняется",
			"count.total.one": "{count} субагент",
			"count.total.other": "{count} субагентов",
			"diagnostic.corrupt": "повреждённая запись сеанса",
			"diagnostic.unavailable": "запись сеанса временно недоступна",
			"diagnostic.unsupported": "неподдерживаемая версия записи субагента",
			"duration.days": "{days} дн",
			"duration.daysHours": "{days} дн {hours} ч",
			"duration.exactDays": "{days} дн {hours} ч {minutes} мин {seconds} с",
			"duration.exactTitle": "Суммарное активное время: {duration}",
			"duration.hours": "{hours} ч {minutes} мин {seconds} с",
			"duration.minutes": "{minutes} мин {seconds} с",
			"duration.months": "~{months} мес",
			"duration.monthsDays": "~{months} мес {days} дн",
			"duration.seconds": "{seconds} с",
			"duration.years": "~{years} г",
			"duration.yearsMonths": "~{years} г {months} мес",
			"load.error": "Не удалось загрузить субагентов",
			"loading.aria": "Загрузка субагентов",
			"loading.label": "Загрузка субагентов…",
			"mode.continuable": "продолжаемый",
			"mode.oneShot": "одноразовый",
			"readonly.body": "Родительский сеанс недоступен; откройте его, чтобы продолжить отправку сообщений.",
			"readonly.oneShot.body": "Одноразовые задачи не принимают продолжений; просмотрите полную запись выполнения здесь.",
			"readonly.oneShot.title": "Запись одноразового субагента",
			"readonly.title": "Этот субагент пока доступен только для чтения",
			"retry": "Повторить",
			"tree.aria": "Сеансы субагентов"
		},
			"trajectory": {
			"toolbar.actualTime": "Фактическое время",
			"toolbar.aria": "Панель траектории",
			"toolbar.calls": "Вызовы",
			"toolbar.collapseCalls": "Свернуть вызовы",
			"toolbar.collapseTurns": "Свернуть ходы",
			"toolbar.duration": "Длительность",
			"toolbar.expandCalls": "Развернуть вызовы",
			"toolbar.expandTurns": "Развернуть ходы",
			"toolbar.search": "Поиск по траектории",
			"toolbar.searchPlaceholder": "Поиск",
			"toolbar.turns": "Ходы",
			"toolbar.useActualDuration": "Использовать фактическую длительность",
			"toolbar.useEqualWidth": "Операции одинаковой ширины",
			"view.trajectory": "Траектория"
		},
			"workflowRun": {
			"member.empty": "Пустое имя участника",
			"member.open": "Открыть {name}",
			"phase.empty": "Пустое название фазы",
			"phase.unassigned": "Без фазы",
			"run.empty": "Участники не запущены",
			"run.members.one": "{count} участник",
			"run.members.other": "{count} участников",
			"run.title": "{name}",
			"status.cancelled": "Отменено",
			"status.completed": "Завершено",
			"status.failed": "Не выполнено",
			"status.interrupted": "Прервано",
			"status.running": "Выполняется",
			"statusCount.cancelled": "Отменено: {count}",
			"statusCount.completed": "Завершено: {count}",
			"statusCount.failed": "Не выполнено: {count}",
			"statusCount.interrupted": "Прервано: {count}",
			"statusCount.running": "Выполняется: {count}"
		},
			"workspace": {
			"actions.newSession.aria": "Новый чат в {name}",
			"actions.session.aria": "Действия с чатом {name}",
			"actions.workspace.aria": "Действия с рабочей папкой {name}",
			"conflict.named": "Рабочая папка «{name}» уже существует.",
			"date.ymd": "{y}-{m}-{d}",
			"delete.desc": "Это удалит «{name}» из списка рабочих папок. Папка и журналы чатов будут сохранены. Её чаты появятся в группе «Без группы».",
			"delete.pending": "Удаление рабочей папки…",
			"delete.workspace": "Удалить рабочую папку",
			"empty.noMatches": "Нет совпадений",
			"empty.none": "Чатов пока нет",
			"field.sessionName": "Название чата",
			"field.workspaceName": "Название рабочей папки",
			"folderError.retry": "Выбрать снова",
			"folderError.title": "Не удалось открыть папку",
			"group.ungrouped": "Без группы",
			"groupBy.flat": "Одним списком",
			"groupBy.label": "Группировать по",
			"groupBy.workspace": "Рабочая папка",
			"hover.copied": "Скопировано",
			"hover.created": "Создан {time}",
			"menu.addWorkspace": "Добавить рабочую папку…",
			"menu.archiveSession": "Архивировать чат",
			"menu.fork": "Ответвить чат",
			"orderBy.label": "Сортировать по",
			"orderBy.manual": "Вручную",
			"orderBy.updated": "Дата изменения",
			"picker.loading": "Загрузка рабочих папок…",
			"rename": "Переименовать",
			"rename.session.title": "Переименовать чат",
			"rename.workspace.title": "Переименовать рабочую папку",
			"search.clear": "Очистить поиск",
			"search.hasMore": "Показаны первые {n} результатов. Уточните запрос.",
			"search.noMatches": "Нет подходящих чатов",
			"search.pending": "Поиск по истории чатов…",
			"search.placeholder": "Поиск чатов...",
			"search.results.aria": "Результаты поиска",
			"search.sessions.aria": "Поиск чатов",
			"search.unavailable": "Поиск по содержимому временно недоступен. Показываем совпадения по названиям.",
			"section.sessions": "Чаты",
			"section.workspaces": "Рабочие папки",
			"session.new": "Новый чат",
			"sessions.collapse": "Показать меньше",
			"sessions.count.one": "{n} чат",
			"sessions.count.other": "{n} чатов",
			"sessions.expand": "Показать ещё {n} чатов",
			"status.completed": "Завершено",
			"status.idle": "Ожидание",
			"status.planReview": "План ожидает проверки",
			"status.running": "Выполняется",
			"status.subagentsRunning.one": "{n} субагент выполняется",
			"status.subagentsRunning.other": "{n} субагентов выполняется",
			"status.waitingAnswer": "Ожидание ответа",
			"status.waitingApproval": "Ожидание подтверждения",
			"time.ago": "{t} назад",
			"time.days": "{n} дн",
			"time.hours": "{n} ч",
			"time.minutes": "{n} мин",
			"time.months": "{n} мес",
			"time.now": "сейчас",
			"time.years": "{n} г",
			"viewOptions.label": "Параметры просмотра",
			"workspace.add": "Добавить рабочую папку"
		}
		};
		//#endregion

		/** Required service: the locale registry (provides `ctx.locale`). */
		const inject = ["locale"];

		/**
		 * Register every Russian dictionary. Runs after the locale plugin
		 * activates (inject edge); the untyped single-locale form
		 * `register(ns, "ru", dict)` is used because `ru` is not a shipped
		 * LocaleId. Missing keys fall back through the standard chain
		 * (ns.zh → common.ru → common.zh → the key itself).
		 * @param ctx - client cordis context.
		 */
		function apply(ctx) {
			ctx.effect(() => {
				const disposers = [];
				for (const [ns, dict] of Object.entries(DICTIONARIES)) {
					disposers.push(ctx.locale.register(ns, "ru", dict));
				}
				return () => { for (const dispose of disposers) dispose(); };
			}, "dsh-locale-ru: dictionaries");
		}

		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	}
});
